# Generated by Django 5.0.1 on 2024-10-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='list',
            new_name='listing',
        ),
    ]
