# Generated by Django 5.0.1 on 2024-10-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_list_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='categroy',
            new_name='category',
        ),
    ]
